[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stacking = "62t5hLMRW19m1c9Th9JbdYvYeJQsKmzWnEVk2qExbt4b"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"

[hooks]
