[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "8oWMa5rkb5cEyfwUmFK6ozTGYFdjmfxvDr9QDMZCcn58"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
